/**
 * @file led_ctrl.c
 * @brief onboard LED controller implementation for STM32.
 * @details This file checks the shared register file's LED Control index and
 *          applies physical voltage levels to Port C, Pin 13 to drive the LED.
 */

#include "led_ctrl.h"
#include "sensor_regmap.h"

void LED_Init(void)
{
    /* 
     * GPIO initialization for GPIOC Pin 13 is handled inside main.c via MX_GPIO_Init()
     * generated by STM32CubeMX, so no additional configuration is required here.
     */
}

void LED_Process(volatile uint8_t *reg_file)
{
    if (reg_file != NULL)
    {
        /* 
         * Read the LED control register byte.
         * Note: A single byte read in 32-bit ARM Cortex-M4 architectures is naturally
         * atomic, so we do not need to disable interrupts here.
         */
        uint8_t led_ctrl = reg_file[REGMAP_ADDR_LED_CTRL];

        /* 
         * On the STM32F411 BlackPill, the user LED is connected to PC13 in an
         * active-low configuration.
         * - Resetting the pin (0V) completes the circuit to ground, turning the LED ON.
         * - Setting the pin (3.3V) cuts current flow, turning the LED OFF.
         */
        if (led_ctrl == REGMAP_LED_CTRL_ON_VALUE)
        {
            HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET); /* 0V: LED ON */
        }
        else if (led_ctrl == REGMAP_LED_CTRL_OFF_VALUE)
        {
            HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);   /* 3.3V: LED OFF */
        }
    }
}

